defmodule Mix.Tasks.Bond.Audit do
  @shortdoc "Reports which public functions carry a contract, and which carry none"

  @moduledoc """
  Which public functions carry a Bond contract, and which carry none.

  The one thing `Bond.Coverage` structurally cannot tell you. Its table reports
  assertions that **ran**, so it is a report about contracts that exist: a
  function nobody contracted appears nowhere in it, and neither does the module
  it lives in.

  That absence is the failure mode the contract-writing rules single out as the
  dangerous one, precisely because nothing shows it:

  > The failure mode is one-sided: a codebase with too few contracts looks
  > exactly like one that never needed them, so careful screening
  > under-contracts by default and nobody notices.

  This turns it into a number.

      mix bond.audit                 # the summary
      mix bond.audit --verbose       # and every uncontracted function
      mix bond.audit --only Tidal    # restrict to matching module names
      mix bond.audit --min 40        # exit non-zero below 40%, for a ratchet

  ## It reads the compiler, not the source

  Every module that `use Bond` exports a `__bond_contracted__/0` reflection
  listing the functions it contracted, built by the compiler from what it
  actually annotated. Nothing here parses Elixir.

  That matters more than it sounds. A source-parsing audit cannot see a function
  generated by a macro, a module that acquired `use Bond` through some *other*
  `__using__`, or a `defdelegate` — and it has to guess at `elixirc_paths` and
  umbrella layouts. The compiler already knows.

  A module that uses Bond and contracts nothing exports `%{}`, which is a
  different answer from not using Bond at all, and the more interesting one.

  ## What it counts, and what it deliberately does not

  The denominator is **public, non-callback functions in modules that use Bond**.
  Three exclusions, each because including it would measure something else:

    * A module that does not use Bond cannot carry a contract. Adding `use Bond`
      to a module is a separate decision from contracting a function in it.
    * `defp` is reported but not counted. Private functions can and should carry
      contracts; they are not part of a module's promise to its callers, so a
      density over them answers a different question.
    * `@impl` callbacks are counted apart. What a callback promises is the
      *behaviour's* to state — see `Bond.Behaviour` — so their absence from an
      implementation's own contracts is not the same finding. They are detected
      from the module's `@behaviour` attributes rather than from `@impl`, which
      is both more accurate and available at runtime.

  A function that appears in the reflection carrying **only** a module
  `@invariant` is counted apart as well. Bond checks that invariant around it, so
  it is real coverage; but an invariant is a law about the *type* rather than a
  promise about any one function, and merging the two would flatter the number.

  ## It is a prompt, not a verdict

  A bare function is a **question** — "what does this promise?" — and some honest
  answers are "nothing beyond its `@spec`". The reasons to decline a contract are
  short: it is unsound, it is unreachable, or the specification does not warrant
  it. "There are a lot of them" is not among them, so a large count here is a
  backlog rather than a defect.
  """

  use Mix.Task

  @impl Mix.Task
  def run(argv) do
    {opts, _rest} =
      OptionParser.parse!(argv, strict: [verbose: :boolean, only: :string, min: :integer])

    Mix.Task.run("compile")

    modules =
      app_modules()
      |> Enum.filter(&uses_bond?/1)
      |> filter(opts[:only])
      |> Enum.map(&audit/1)
      |> Enum.sort_by(&{-length(&1.bare), &1.module})

    report(modules, opts)
    ratchet(modules, opts[:min])
  end

  defp app_modules do
    app = Mix.Project.config()[:app]

    if is_atom(app) and not is_nil(app) do
      _already_loaded_is_fine = Application.load(app)
      Application.spec(app, :modules) || []
    else
      []
    end
  end

  defp uses_bond?(module) do
    Code.ensure_loaded?(module) and function_exported?(module, :__bond_contracted__, 0)
  end

  defp filter(modules, nil), do: modules

  defp filter(modules, pattern),
    do: Enum.filter(modules, &String.contains?(inspect(&1), pattern))

  # ── reading a module ──────────────────────────────────────────────────────

  defp audit(module) do
    contracted = covered(module.__bond_contracted__())
    callbacks = callbacks(module)

    public =
      Enum.reject(module.__info__(:functions), &(reflection?(&1) or &1 in callbacks))

    %{
      module: module,
      public: public,
      held: Enum.filter(public, &own_assertions?(contracted, &1)),
      invariant_only: Enum.filter(public, &invariant_only?(contracted, &1)),
      bare:
        Enum.reject(public, &(own_assertions?(contracted, &1) or invariant_only?(contracted, &1))),
      callbacks: length(callbacks)
    }
  end

  # Machine-generated exports, by Elixir's own naming convention for them: a name
  # both starting and ending in `__`. That covers Bond's `__bond_contracted__/0`,
  # Elixir's `__info__/1` and `__struct__/0`, Ecto's `__schema__/1` and
  # `__changeset__/0`, Phoenix's `__live__/0`, and whatever the next library
  # generates without this needing to know about it.
  #
  # Counting them is not a rounding error. An `Ecto.Schema` exports five or six,
  # so a project with forty schemas would carry two hundred functions nobody
  # wrote into the denominator and report a density a third of the truth — which
  # is exactly what the first version of this task did.
  defp reflection?({name, _arity}) do
    name = Atom.to_string(name)

    (String.starts_with?(name, "__") and String.ends_with?(name, "__")) or
      name == "module_info"
  end

  # From `@behaviour` rather than `@impl`: the attribute survives into the BEAM,
  # and a behaviour names its callbacks itself, so this needs no source.
  defp callbacks(module) do
    module.__info__(:attributes)
    |> Keyword.get_values(:behaviour)
    |> List.flatten()
    |> Enum.filter(&Code.ensure_loaded?/1)
    |> Enum.flat_map(fn behaviour ->
      if function_exported?(behaviour, :behaviour_info, 1),
        do: behaviour.behaviour_info(:callbacks),
        else: []
    end)
    |> Enum.uniq()
  end

  # Coverage is decided per **name**, not per `{name, arity}`, because a default
  # argument exports an arity nobody wrote: `def f(a, b \\\\ x)` exports `f/1` and
  # `f/2`, Bond contracts one of them, and the other would be reported bare. On
  # this project's own library that was 64 of 395 supposed gaps.
  #
  # The residual imprecision is in the safe direction. A genuinely bare function
  # with defaults is still counted once per exported arity, so the tool
  # over-reports work rather than hiding it — and a name whose arities really are
  # unrelated functions is vanishingly rare in Elixir.
  defp covered(contracted) do
    Map.new(contracted, fn {{name, _arity}, entry} -> {name, entry} end)
  end

  defp own_assertions?(covered, {name, _arity}) do
    match?(%{own_assertions: n} when n > 0, Map.get(covered, name))
  end

  defp invariant_only?(covered, {name, _arity}) do
    match?(%{own_assertions: 0, invariants: n} when n > 0, Map.get(covered, name))
  end

  # ── reporting ─────────────────────────────────────────────────────────────

  defp report([], _opts),
    do: Mix.shell().info("No modules using Bond were found in this application.")

  defp report(modules, opts) do
    total = modules |> Enum.flat_map(& &1.public) |> length()
    held = modules |> Enum.flat_map(& &1.held) |> length()
    invariant_only = modules |> Enum.flat_map(& &1.invariant_only) |> length()
    callbacks = Enum.reduce(modules, 0, &(&1.callbacks + &2))

    Mix.shell().info("""

    Bond contract density — #{length(modules)} modules using Bond

      Public, non-callback functions. A function carrying only a module
      @invariant is counted apart: that is a law about the type, not a promise
      about the function.
    """)

    modules
    |> Enum.reject(&(&1.public == []))
    |> Enum.each(fn module ->
      Mix.shell().info(line(module))
      if opts[:verbose], do: Enum.each(module.bare, &Mix.shell().info(detail(&1)))
    end)

    Mix.shell().info("""
      #{String.duplicate("-", 68)}
      #{String.pad_trailing("overall", 50)}#{tally(held, total)}

      #{total - held - invariant_only} of #{total} carry no contract of their own.
      #{invariant_only} covered by a module invariant only; #{callbacks} callback(s) counted separately.
    #{hint(opts[:verbose])}\
    """)
  end

  defp hint(true), do: ""
  defp hint(_not_verbose), do: "\n  --verbose lists every uncontracted function.\n"

  defp line(module) do
    "  " <>
      String.pad_trailing(inspect(module.module), 48) <>
      tally(length(module.held), length(module.public))
  end

  defp detail({name, arity}), do: "        #{name}/#{arity}"

  defp tally(held, total) do
    percent = if total == 0, do: 0, else: round(held / total * 100)

    String.pad_leading("#{held}/#{total}", 9) <> String.pad_leading("#{percent}%", 6)
  end

  # ── the optional ratchet ──────────────────────────────────────────────────

  defp ratchet(_modules, nil), do: :ok

  defp ratchet(modules, minimum) do
    total = modules |> Enum.flat_map(& &1.public) |> length()
    held = modules |> Enum.flat_map(& &1.held) |> length()
    percent = if total == 0, do: 100, else: round(held / total * 100)

    if percent < minimum do
      Mix.raise("contract density is #{percent}%, below the required #{minimum}%")
    end

    :ok
  end
end
