defmodule Bond.GeneratedHeadsTest do
  @moduledoc """
  #105: `@invariant` on a module whose clause heads are generated by a macro.

  The reported case is `use Ecto.Schema`, which rules out `@invariant` on the most common
  struct type in a Phoenix app. Nothing about it is Ecto-specific, though: the trigger is a
  head built with `unquote_splicing/1`, whose variables carry the `quote` context rather than
  the module's, so the invariant wrapper bound its canonical name as one variable and
  referenced it as another. See `BondTest.GeneratedHeads` for the shapes.

  That the fixture module compiles at all is most of this test — before the fix it did not,
  which failed the whole suite rather than one case. What is asserted here is the other half:
  that weaving still does its job through a generated head.
  """

  use ExUnit.Case, async: true

  alias BondTest.GeneratedHeads, as: G

  describe "generated heads that do not take the struct" do
    test "a spliced wildcard position dispatches normally" do
      assert G.meta(:fields, nil) == [:n]
      assert G.meta(:source, :anything) == "generated_heads"
    end

    test "a spliced named variable is still bound for the body" do
      assert G.tagged(:a, :one) == {:one, :a}
      assert G.tagged(:b, :many) == {:many, :b}
    end
  end

  describe "generated heads that do take the struct" do
    test "the entry check fires" do
      assert_raise Bond.InvariantError, fn -> G.peek(%G{n: -1}) end
      assert G.peek(%G{n: 3}) == 3
    end

    test "the entry check fires through a guarded destructuring head" do
      assert_raise Bond.InvariantError, fn -> G.doubled(%G{n: -5}) end
      assert G.doubled(%G{n: 4}) == 8
    end

    test "the guard on a generated head still selects between clauses" do
      # `n > 1` is false, so dispatch must fall through to the source-written clause
      # rather than the wrapper collapsing to a catch-all.
      assert G.doubled(%G{n: 1}) == :too_small
    end
  end

  describe "invariants on source-written heads are unaffected" do
    test "the exit check still fires" do
      assert_raise Bond.InvariantError, fn -> G.bump(%G{n: -2}) end
      assert G.bump(%G{n: 1}) == %G{n: 2}
    end
  end
end
